apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-pipeline-demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: jenkins-pipeline-demo
  template:
    metadata:
      labels:
        app: jenkins-pipeline-demo
    spec:
      containers:
      - image: zhangchuan/jenkins-pipeline-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: jenkins-demo
        env:
        - name: branch
          value: <BRANCH_NAME>
